apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-flipkart-application-config
  namespace: prod
  labels:
    env: prod
    app: flipkart-ms
    layer: frontend
data:
  db-host: cluster-mysql.database
  db-port: 3306
  db-name: my-db