apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-flipkart-hpa
  namespace: prod
  labels:
    env: prod
    app: flipkart-ms
    layer: frontend
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: prod-flipkart-deployment
  targetCPUUtilizationPercentage: 160